---
#
# This could all be one task to push all NCLU at once
- hosts: vtep
  become: yes
  tasks:
    - name: Activate BGP L2VPN EVPN address family
      nclu:
        commands:
          - add bgp l2vpn evpn neighbor swp51-52 activate
          
    - name: Configure advertise-all-vni
      nclu:
        commands:
          - add bgp l2vpn evpn advertise-all-vni
          
    - name: Disable bridge learning on VTEP interfaces
      nclu:
        commands:         
          - add vxlan vni-13 bridge learning off
          - add vxlan vni-24 bridge learning off
        
    - name: Remove LNV configuration on loopback interfaces
      nclu:
        commands:        
          - del loopback lo vxrd-src-ip
          - del loopback lo vxrd-svcnode-ip
                 
- hosts: exit
  become: yes
  tasks:
    - name: Configure exit/routing nodes to advertise gateway
      nclu:
        commands:
          - add bgp l2vpn evpn advertise-default-gw
 
- hosts: spine
  become: yes
  tasks:
    - name: Activate BGP L2VPN EVPN address family
      nclu:
        commands:
          - add bgp l2vpn evpn neighbor swp1-4 activate
          - add bgp l2vpn evpn neighbor swp29-30 activate
          
    - name: Remove LNV Service Node configuration
      nclu:
        commands:        
          - del lnv service-node anycast-ip 10.0.0.200
          - del lnv service-node source {{ ansible_lo.ipv4_secondaries[0].address }}
          
    - name: Remove Unused LNV Anycast Address
      nclu:
        commands:        
          - del loopback lo ip address 10.0.0.200/32
          - del bgp ipv4 unicast network 10.0.0.200/32         
    
#### We have to manually stop and disable vxrd at minimum.  
## NCLU does not currently support disabling/stopping vxrd      
- hosts: vtep
  become: yes
  tasks:       
    - name: Stop and Disable LNV Client (vxrd)
      service:
        name: vxrd
        enabled: no
        state: stopped
           
- hosts: spine
  become: yes
  tasks:       
    - name: Stop and Disable LNV Service Node Daemon (vxsnd)
      service:
        name: vxsnd
        enabled: no
        state: stopped
                 
- hosts: network
  become: yes
  tasks:
    - name: Commit & apply all changes
      nclu:
        commit: true
